---
- name: install git command
  hosts: 172.31.3.145
  become: true
  vars:
    var: "git"
  tasks:
  - name: install git
    yum:
      name: "{{var}}"
  - command: mkdir /home/ec2-user/Myfile
    
