---
- name: Practicing on task
  hosts: localhost
  vars_prompt:
    - name: var1
      prompt: enter var1?
    - name: var2
      prompt: enter var2?
    - name: var3
      prompt: enter var3?
  tasks:
  - name: Print the value of var1
    debug:
      msg: "{{ var2 }}"
    when: var1 > var2
  - name: Print the value of  var3
    debug:
      msg: "{{ var3 }}"
    when: var2 > var3
  - name: Print the value of var3
    debug:
      msg: "{{ var1 }}"
    when: var3 > var1
